"""Data contracts and workbook metadata for qsr-audit."""

from qsr_audit.contracts.workbook import (
    AI_STRATEGY_REGISTRY_COLUMN_MAP,
    AI_STRATEGY_SHEET,
    BRONZE_RAW_SHEET_STEMS,
    CANONICAL_BRAND_NAME_ALIASES,
    CORE_BRAND_METRICS_COLUMN_MAP,
    CORE_BRAND_METRICS_SHEET,
    DATA_NOTES_COLUMN_MAP,
    DATA_NOTES_SHEET,
    KEY_FINDINGS_SECTION_MARKER,
    ORIGINAL_CHINESE_COLUMNS,
    REQUIRED_WORKBOOK_SHEETS,
    SILVER_OUTPUT_FILES,
)

__all__ = [
    "AI_STRATEGY_REGISTRY_COLUMN_MAP",
    "AI_STRATEGY_SHEET",
    "BRONZE_RAW_SHEET_STEMS",
    "CANONICAL_BRAND_NAME_ALIASES",
    "CORE_BRAND_METRICS_COLUMN_MAP",
    "CORE_BRAND_METRICS_SHEET",
    "DATA_NOTES_COLUMN_MAP",
    "DATA_NOTES_SHEET",
    "KEY_FINDINGS_SECTION_MARKER",
    "ORIGINAL_CHINESE_COLUMNS",
    "REQUIRED_WORKBOOK_SHEETS",
    "SILVER_OUTPUT_FILES",
]
